const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const words={
 'zh-CN':{title:'链上收款',note:'地址按链类型共用；单个网络可另设地址。启用后还需添加「虚拟货币」支付方式。',evm:'EVM 共用地址',tron:'TRON 地址',solana:'Solana 地址',tolerance:'允许少付（%）',lifetime:'订单有效期（分钟）',hours:'最长确认时间（小时）',late:'有效期后仍核验已转账交易',networks:'收款网络与币种',advanced:'高级配置：节点、合约和确认策略',test:'检查节点与代币',testing:'正在检查…',ok:'节点与代币检查通过',bad:'检查未通过',add:'添加网络',json:'网络配置 JSON 无效',help:'修改节点、代币合约、精度或网络地址。新代币填写 asset、label、contract、decimals、enabled。请先检查节点，再启用。',events:'链事件 Webhook（可选）',hookNote:'外部链事件只唤醒服务器核验，不能直接确认付款。到账通知在「通知」中配置。',secret:'链事件签名密钥（至少 32 字符）',endpoint:'事件接收地址',save:'保存'},
 'zh-TW':{title:'鏈上收款',note:'地址依鏈類型共用；各網路可另設地址。啟用後還需新增「虛擬貨幣」支付方式。',evm:'EVM 共用地址',tron:'TRON 地址',solana:'Solana 地址',tolerance:'允許少付（%）',lifetime:'訂單有效期（分鐘）',hours:'最長確認時間（小時）',late:'有效期後仍驗證已轉帳交易',networks:'收款網路與幣種',advanced:'進階設定：節點、合約及確認策略',test:'檢查節點與代幣',testing:'正在檢查…',ok:'節點與代幣檢查通過',bad:'檢查未通過',add:'新增網路',json:'網路設定 JSON 無效',help:'可修改節點、代幣合約、精度或網路地址。新代幣填寫 asset、label、contract、decimals、enabled。請先檢查節點，再啟用。',events:'鏈事件 Webhook（選填）',hookNote:'外部鏈事件只喚醒伺服器驗證，無法直接確認付款。入帳通知在「通知」中設定。',secret:'鏈事件簽章金鑰（至少 32 字元）',endpoint:'事件接收地址',save:'儲存'},
 en:{title:'On-chain payments',note:'Addresses are shared by chain family, with optional overrides per network. Add a Crypto payment method after enabling networks.',evm:'Shared EVM address',tron:'TRON address',solana:'Solana address',tolerance:'Underpayment tolerance (%)',lifetime:'Payment lifetime (minutes)',hours:'Confirmation deadline (hours)',late:'Verify transferred payments after expiry',networks:'Networks and tokens',advanced:'Advanced: nodes, contracts and finality',test:'Check node and tokens',testing:'Checking…',ok:'Node and token checks passed',bad:'Check failed',add:'Add network',json:'Invalid network JSON',help:'Edit nodes, token contracts, precision or receiving-address overrides. New tokens require asset, label, contract, decimals and enabled. Check before enabling.',events:'Chain-event webhook (optional)',hookNote:'External events only wake verification; they cannot confirm payments. Configure outgoing notifications under Notifications.',secret:'Chain-event signing secret (at least 32 characters)',endpoint:'Event endpoint',save:'Save'}
};
export function createCryptoAdmin({api,getLocale,markDirty,notify}){
 let config=null;
 const t=k=>words[getLocale()]?.[k]||words.en[k]||k;
 const input=(label,name,value,type='text',extra='')=>`<div class="field"><label for="field-${name}">${esc(label)}</label><input id="field-${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
 function markup(n,i){return `<article class="crypto-network" data-network-index="${i}"><label class="check-field"><input type="checkbox" name="crypto-net-${i}" ${n.enabled?'checked':''}><span>${esc(n.name)} <small>${esc(n.family)}</small></span></label><div class="check-group">${(n.tokens||[]).map(token=>`<label class="check-field"><input type="checkbox" name="crypto-token-${i}-${esc(token.asset)}" ${token.enabled?'checked':''}><span>${esc(token.label||token.asset)}</span></label>`).join('')}</div><details><summary>${esc(t('advanced'))}</summary><label class="sr-only" for="field-crypto-json-${i}">${esc(n.name)} JSON</label><textarea id="field-crypto-json-${i}" name="crypto-json-${i}" rows="12" spellcheck="false">${esc(JSON.stringify(n,null,2))}</textarea><p class="help">${esc(t('help'))}</p></details><button type="button" class="quiet" data-crypto-check="${i}">${esc(t('test'))}</button><p class="help" data-crypto-health="${i}" role="status"></p></article>`;}
 function render(c){
  config=structuredClone(c);
  $('#crypto-form').innerHTML=`<div class="config-section"><h2>${esc(t('title'))}</h2><p class="help">${esc(t('note'))}</p><div class="form-grid">${['evm','tron','solana'].map(f=>input(t(f),`crypto-address-${f}`,c.addresses?.[f]||'','text','autocomplete="off" spellcheck="false"')).join('')}${input(t('tolerance'),'crypto-tolerance',c.tolerance_bps/100,'number','min="0" max="10" step="0.01" required')}${input(t('lifetime'),'crypto-lifetime',c.lifetime_minutes,'number','min="5" max="1440" step="1" required')}${input(t('hours'),'crypto-hours',c.confirmation_hours,'number','min="1" max="168" step="1" required')}</div><label class="check-field"><input type="checkbox" name="crypto-late" ${c.accept_late?'checked':''}><span>${esc(t('late'))}</span></label></div><div class="config-section"><h2>${esc(t('networks'))}</h2><div id="crypto-networks">${c.networks.map(markup).join('')}</div><button type="button" class="quiet" id="crypto-add-network">${esc(t('add'))}</button></div><details class="config-section"><summary>${esc(t('events'))}</summary><p class="help">${esc(t('hookNote'))}</p><p class="help">${esc(t('endpoint'))}: <code>${esc(location.origin+'/api/crypto/events')}</code></p>${input(t('secret'),'crypto-secret',c.event_secret||'','password','autocomplete="new-password" minlength="32" maxlength="256"')}</details><div class="form-actions"><button type="submit" class="primary">${esc(t('save'))}</button></div>`;
  $('#crypto-add-network').addEventListener('click',()=>{try{const next=collect();next.networks.push({id:`network-${crypto.randomUUID().slice(0,8)}`,name:'New network',family:'evm',enabled:false,recipient:'',chain_id:1,rpc_url:'https://ethereum-rpc.publicnode.com',ws_url:'',api_key:'',explorer:'https://etherscan.io/tx/',confirmations:12,finality:'finalized',native_symbol:'ETH',tokens:[]});render(next);markDirty();$('#crypto-networks article:last-child details').open=true;}catch(e){notify(e.message,true);}});
 }
 function network(i,data=new FormData($('#crypto-form'))){
  let n;try{n=JSON.parse(data.get(`crypto-json-${i}`));if(!n || !Array.isArray(n.tokens))throw new Error();}catch{throw new Error(`${t('json')} · ${config.networks[i].name}`);}
  n.enabled=data.has(`crypto-net-${i}`);
  n.tokens=n.tokens.map(token=>({...token,enabled:config.networks[i].tokens.some(old=>old.asset===token.asset)?data.has(`crypto-token-${i}-${token.asset}`):token.enabled===true}));
  return n;
 }
 function collect(){
  const data=new FormData($('#crypto-form')),raw=String(data.get('crypto-tolerance'));
  if(!/^\d+(?:\.\d{1,2})?$/.test(raw))throw new Error(t('tolerance'));
  const [whole,fraction='']=raw.split('.');
  return {...config,addresses:Object.fromEntries(['evm','tron','solana'].map(f=>[f,String(data.get(`crypto-address-${f}`)||'').trim()])),tolerance_bps:Number(whole)*100+Number(fraction.padEnd(2,'0')),lifetime_minutes:Number(data.get('crypto-lifetime')),confirmation_hours:Number(data.get('crypto-hours')),accept_late:data.has('crypto-late'),event_secret:String(data.get('crypto-secret')||'').trim(),networks:config.networks.map((_,i)=>network(i,data))};
 }
 $('#crypto-form').addEventListener('click',async event=>{
  const button=event.target.closest('[data-crypto-check]');if(!button || button.disabled)return;
  const i=Number(button.dataset.cryptoCheck),result=$(`[data-crypto-health="${i}"]`);button.disabled=true;result.textContent=t('testing');
  try{const r=await api('/api/admin/crypto/check',{method:'POST',body:{network:network(i)}});result.textContent=r.ok?t('ok'):`${t('bad')} · ${r.reason}`;}catch(e){result.textContent=e.message;}finally{button.disabled=false;}
 });
 return {render,collect};
}
